#!/bin/bash

# Convert kernel/rootfs images generated by build-yocto-qemux86
# into a .VDI image suitable to be executed from VirtualBox

# BIG FAT WARNING
# A few dangerous commands are executed as sudo and may destroy your host filesystem if buggy.
# USE AT YOUR OWN RISK - YOU HAVE BEEN WARNED!!!

# Prerequisites:
#    qemu-img
#    kpartx
#    grub-install
#    fdisk
#    sudo

TOPDIR=$PWD/tmp/build-gemini-5.0.2-qemux86

MACHINE=qemux86
FSTYPE=tar.bz2
KERNEL=$TOPDIR/tmp/deploy/images/$MACHINE/bzImage-$MACHINE.bin
ROOTFS=$TOPDIR/tmp/deploy/images/$MACHINE/gemini-image-$MACHINE.$FSTYPE

RAW_IMAGE=test.raw
VDI_IMAGE=test.vdi

MNT_ROOTFS=/tmp/rootfs

set -e
#set -x

# Create QEMU image
# See http://en.wikibooks.org/wiki/QEMU/Images

qemu-img create -f raw $RAW_IMAGE 256M

fdisk $RAW_IMAGE <<END
n
p
1


a
1
p
w
END

#sfdisk -l $RAW_IMAGE
fdisk -l $RAW_IMAGE

TMPFILE1=/tmp/kpartx-$$.tmp

# See http://stackoverflow.com/questions/1419489/loopback-mounting-individual-partitions-from-within-a-file-that-contains-a-parti
sudo kpartx -v -a $RAW_IMAGE >$TMPFILE1

#echo "DBG: Contents of $TMPFILE1:"
#cat $TMPFILE1

# loop0p1
ROOTPART=`cut -d' ' -f3 $TMPFILE1`
BLOCKDEV=`cut -d' ' -f8 $TMPFILE1`
echo "DBG: ROOTPART=$ROOTPART"
echo "DBG: BLOCKDEV=$BLOCKDEV"

sudo mkfs -t ext3 /dev/mapper/$ROOTPART

mkdir -p $MNT_ROOTFS
sudo mount -o loop /dev/mapper/$ROOTPART $MNT_ROOTFS

TMPFILE2=/tmp/losetup-$$.tmp

sudo losetup -av >$TMPFILE2

#echo "DBG: Contents of $TMPFILE2:"
#cat $TMPFILE2

# TODO: Copy kernel to $MNT_ROOTFS/boot
sudo install -m755 -d $MNT_ROOTFS/boot
sudo install -m644 -o 0 -v $KERNEL $MNT_ROOTFS/boot

# Extract rootfs
#sudo tar xvfj $ROOTFS -C $MNT_ROOTFS

#echo "TODO:"
# TODO: Create grub.cfg to MNT_ROOTFS/boot/grub
# grub-mkimage ???

sudo grub-install --boot-directory=$MNT_ROOTFS/boot $BLOCKDEV

echo "DBG: Contents of $MNT_ROOTFS:"
ls -la $MNT_ROOTFS

echo "DBG: Contents of $MNT_ROOTFS/boot:"
du -sh $MNT_ROOTFS/boot
ls -la $MNT_ROOTFS/boot
#ls -laR $MNT_ROOTFS/boot

echo "DBG: Disk space on $MNT_ROOTFS:"
df -h $MNT_ROOTFS

sudo umount $MNT_ROOTFS

sudo kpartx -d $RAW_IMAGE

qemu-img convert -f raw -O vdi $RAW_IMAGE $VDI_IMAGE

# TODO: Test: Run QEMU against VDI_IMAGE
# TODO: Test: Run VirtualBox against VDI_IMAGE

sudo losetup -av

# See also: http://libguestfs.org/

rm $TMPFILE1
rm $TMPFILE2

exit 0;

# EOF
